namespace NetShare.WLAN.WinAPI
{
	public enum WLAN_NOTIFICATION_CODE_MSM
	{
		START,
		ASSOCIATING,
		ASSOCIATED,
		AUTHENTICATING,
		CONNECTED,
		ROAMING_START,
		ROAMING_END,
		RADIO_STATE_CHANGE,
		SIGNAL_QUALITY_CHANGE,
		DISASSOCIATING,
		DISCONNECTED,
		PEER_JOIN,
		PEER_LEAVE,
		ADAPTER_REMOVAL,
		ADAPTER_OPERATION_MODE_CHANGE,
	}
}
