namespace NetShare.Wlan.WinAPI
{
	public enum WLAN_INTF_OPCODE : uint
	{
		AUTOCONF_START,
		AUTOCONF_ENABLED,
		BACKGROUND_SCAN_ENABLED,
		MEDIA_STREAMING_MODE,
		RADIO_STATE,
		BSS_TYPE,
		INTERFACE_STATE,
		CURRENT_CONNECTION,
		CHANNEL_NUMBER,
		SUPPORTED_INFRASTRUCTURE_AUTH_CIPHER_PAIRS,
		SUPPORTED_ADHOC_AUTH_CIPHER_PAIRS,
		SUPPORTED_COUNTRY_OR_REGION_STRING_LIST,
		CURRENT_OPERATION_MODE,
		SUPPORTED_SAFE_MODE,
		CERTIFIED_SAFE_MODE,
		AUTOCONF_END									= 0x0fffffff,
		MSM_START										= 0x10000100,
		STATISTICS,
		RSSI,
		MSM_END											= 0x1fffffff,
		SECURITY_START									= 0x20010000,
		SECURITY_END									= 0x2fffffff,
		IHV_START										= 0x30000000,
		IHV_END											= 0x3fffffff,
	}
}
