namespace NetShare.WLAN.WinAPI
{
	public enum WLAN_INTERFACE_STATE
	{
		NOT_READY,
		CONNECTED,
		AD_HOC_NETWORK_FORMED,
		DISCONNECTING,
		DISCONNECTED,
		ASSOCIATING,
		DISCOVERING,
		AUTHENTICATING,
	}
}